export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const LOGIN_REQUEST_CHECK = "LOGIN_REQUEST_CHECK";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ADD_QUESTION_TO_USER = "ADD_QUESTION_TO_USER";
export const ADD_ANSWER_TO_USER = "ADD_ANSWER_TO_USER";
export const LOG_OUT = "LOG_OUT";
